// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package post

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PostRPCClient is the client API for PostRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PostRPCClient interface {
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*PostResponse, error)
}

type postRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewPostRPCClient(cc grpc.ClientConnInterface) PostRPCClient {
	return &postRPCClient{cc}
}

func (c *postRPCClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, "/post.PostRPC/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostRPCServer is the server API for PostRPC service.
// All implementations must embed UnimplementedPostRPCServer
// for forward compatibility
type PostRPCServer interface {
	CreatePost(context.Context, *CreatePostRequest) (*PostResponse, error)
	mustEmbedUnimplementedPostRPCServer()
}

// UnimplementedPostRPCServer must be embedded to have forward compatible implementations.
type UnimplementedPostRPCServer struct {
}

func (UnimplementedPostRPCServer) CreatePost(context.Context, *CreatePostRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (UnimplementedPostRPCServer) mustEmbedUnimplementedPostRPCServer() {}

// UnsafePostRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostRPCServer will
// result in compilation errors.
type UnsafePostRPCServer interface {
	mustEmbedUnimplementedPostRPCServer()
}

func RegisterPostRPCServer(s grpc.ServiceRegistrar, srv PostRPCServer) {
	s.RegisterService(&PostRPC_ServiceDesc, srv)
}

func _PostRPC_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostRPCServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.PostRPC/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostRPCServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PostRPC_ServiceDesc is the grpc.ServiceDesc for PostRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "post.PostRPC",
	HandlerType: (*PostRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _PostRPC_CreatePost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/post/post.proto",
}
